-- INSERT INTO product (name, brand, category, description, image, price, id)
-- VALUES ('iPhone X', 'Apple', 'Smart Phone', '64GB, iOS 11, space gray', 'iphonex.jpg', 999.00, 0),
--        ('iPhone 8', 'Apple', 'Smart Phone', '64GB, iOS 11, silver', 'iphone8.jpg', 799.00, 1),
--        ('C7 OLED', 'LG', 'TV', '65" Smart TV', 'lg_tv.jpg', 3000.00, 2),
--        ('Macbook Pro', 'Apple', 'Computer', '15 laptop, 512GB SSD', 'macbahonex.jpg', 2800.00, 3);
--
